sonar.projectKey=oficina-tech-challenge
sonar.projectName=Oficina Tech Challenge
sonar.projectVersion=1.0

# Paths configuration
sonar.sources=src
sonar.tests=test
sonar.language=ts

# Exclusions
sonar.exclusions=**/node_modules/**,**/*.spec.ts,dist/**,coverage/**

# Test and Coverage reporting
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
