export enum ServiceOrderStatus {
    RECEIVED = 'RECEIVED',
    IN_DIAGNOSIS = 'IN_DIAGNOSIS',
    WAITING_APPROVAL = 'WAITING_APPROVAL',
    IN_PROGRESS = 'IN_PROGRESS',
    FINISHED = 'FINISHED',
    DELIVERED = 'DELIVERED',
}